{% set name = "replicate" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/replicate-{{ version }}.tar.gz
  sha256: f718601863ef1f419aa7dcdab1ea8770ba5489b571b86edf840cd506d68758ef

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - httpx >=0.21.0,<1
    - packaging
    - pydantic >1
    - typing-extensions >=4.5.0

test:
  imports:
    - replicate
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://replicate.com
  summary: Python client for Replicate
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/replicate/replicate-python

extra:
  recipe-maintainers:
    - sodre
