{% set name = "replicate" %}
{% set version = "0.33.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/replicate-{{ version }}.tar.gz
  sha256: 79f179aa791072c2141bfc5481b786cdd79e368b53938be7dbd7b07af9c14f6b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - httpx >=0.21.0,<1
    - packaging
    - pydantic >1
    - typing-extensions >=4.5.0

test:
  imports:
    - replicate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://replicate.com
  summary: Python client for Replicate
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/replicate/replicate-python

extra:
  recipe-maintainers:
    - sodre
